insert into Company (id, name, description, id_recruiter) values (1, 'Jamia', 'Unspecified foreign body in pharynx causing other injury, subsequent encounter', 38);
insert into Company (id, name, description, id_recruiter) values (2, 'Twinder', 'Glaucoma secondary to drugs, unspecified eye', 45);
insert into Company (id, name, description, id_recruiter) values (3, 'Edgeify', 'Type 3 fracture of sacrum, subsequent encounter for fracture with delayed healing', 29);
insert into Company (id, name, description, id_recruiter) values (4, 'Twinte', 'Other intraarticular fracture of lower end of unspecified radius, initial encounter for open fracture type IIIA, IIIB, or IIIC', 15);
insert into Company (id, name, description, id_recruiter) values (5, 'Jabberstorm', 'Poisoning by cephalosporins and other beta-lactam antibiotics, assault', 34);
insert into Company (id, name, description, id_recruiter) values (6, 'Jaxbean', 'Passenger injured in collision with other motor vehicles in traffic accident, subsequent encounter', 43);
insert into Company (id, name, description, id_recruiter) values (7, 'Shuffledrive', 'Spondylopathy in diseases classified elsewhere, thoracolumbar region', 40);
insert into Company (id, name, description, id_recruiter) values (8, 'Katz', 'Idiopathic aseptic necrosis of unspecified bone', 17);
insert into Company (id, name, description, id_recruiter) values (9, 'Babbleopia', 'Unspecified open wound of right great toe without damage to nail, subsequent encounter', 50);
insert into Company (id, name, description, id_recruiter) values (10, 'Gigazoom', 'Defects of catalase and peroxidase', 38);
insert into Company (id, name, description, id_recruiter) values (11, 'Livetube', 'Unspecified myringitis, right ear', 9);
insert into Company (id, name, description, id_recruiter) values (12, 'Gabtype', 'Subluxation of metacarpophalangeal joint of left little finger, sequela', 48);
insert into Company (id, name, description, id_recruiter) values (13, 'Quamba', 'Nonrheumatic tricuspid (valve) stenosis', 28);
insert into Company (id, name, description, id_recruiter) values (14, 'Yadel', 'Laceration of prostate, sequela', 16);
insert into Company (id, name, description, id_recruiter) values (15, 'Voonte', 'Other hemoglobinopathies', 2);
insert into Company (id, name, description, id_recruiter) values (16, 'Talane', 'Unspecified fracture of lower end of left ulna, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', 24);
insert into Company (id, name, description, id_recruiter) values (17, 'Browsetype', 'Injury of other specified muscles and tendons at ankle and foot level', 17);
insert into Company (id, name, description, id_recruiter) values (18, 'Eire', 'Subluxation of C0/C1 cervical vertebrae', 25);
insert into Company (id, name, description, id_recruiter) values (19, 'Yadel', 'Fatigue fracture of vertebra, thoracolumbar region, subsequent encounter for fracture with delayed healing', 49);
insert into Company (id, name, description, id_recruiter) values (20, 'Eazzy', 'Displaced comminuted fracture of shaft of right tibia, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with malunion', 33);
insert into Company (id, name, description, id_recruiter) values (21, 'Yodoo', 'Nondisplaced fracture of base of unspecified metacarpal bone', 47);
insert into Company (id, name, description, id_recruiter) values (22, 'Wikivu', 'Laceration of unspecified muscles, fascia and tendons at forearm level, unspecified arm, subsequent encounter', 20);
insert into Company (id, name, description, id_recruiter) values (23, 'Cogilith', 'Drowning and submersion due to being washed overboard from other unpowered watercraft, initial encounter', 3);
insert into Company (id, name, description, id_recruiter) values (24, 'Wikibox', 'Mechanical complication of internal joint prosthesis', 1);
insert into Company (id, name, description, id_recruiter) values (25, 'Trudeo', 'Displaced oblique fracture of shaft of unspecified fibula, subsequent encounter for open fracture type IIIA, IIIB, or IIIC with routine healing', 43);
insert into Company (id, name, description, id_recruiter) values (26, 'Shufflester', 'Car passenger injured in collision with other type car in nontraffic accident', 17);
insert into Company (id, name, description, id_recruiter) values (27, 'Flashspan', 'Juvenile osteochondrosis of hip and pelvis, unspecified, right leg', 35);
insert into Company (id, name, description, id_recruiter) values (28, 'Babbleset', 'Vitamin B12 deficiency anemia due to intrinsic factor deficiency', 29);
insert into Company (id, name, description, id_recruiter) values (29, 'Feedbug', 'Effect of deprivation, unspecified, sequela', 41);
insert into Company (id, name, description, id_recruiter) values (30, 'Fadeo', 'Nondisplaced segmental fracture of shaft of unspecified tibia, subsequent encounter for open fracture type I or II with nonunion', 14);
insert into Company (id, name, description, id_recruiter) values (31, 'Meevee', 'Other fracture of left femur, subsequent encounter for open fracture type I or II with delayed healing', 22);
insert into Company (id, name, description, id_recruiter) values (32, 'Dynabox', 'Staphylococcal arthritis, elbow', 33);
insert into Company (id, name, description, id_recruiter) values (33, 'Browsedrive', 'Osteoarthritis of knee', 5);
insert into Company (id, name, description, id_recruiter) values (34, 'Devbug', 'Puncture wound without foreign body of unspecified front wall of thorax with penetration into thoracic cavity, sequela', 10);
insert into Company (id, name, description, id_recruiter) values (35, 'Photojam', 'Unspecified car occupant injured in collision with pedestrian or animal in nontraffic accident', 13);
insert into Company (id, name, description, id_recruiter) values (36, 'Livefish', 'Retinopathy of prematurity, stage 5, unspecified eye', 30);
insert into Company (id, name, description, id_recruiter) values (37, 'Quire', 'Contracture of muscle, unspecified site', 30);
insert into Company (id, name, description, id_recruiter) values (38, 'Zoomzone', 'Maternal care for breech presentation', 45);
insert into Company (id, name, description, id_recruiter) values (39, 'Skidoo', 'Maternal care for other known or suspected poor fetal growth, unspecified trimester, not applicable or unspecified', 21);
insert into Company (id, name, description, id_recruiter) values (40, 'Pixoboo', 'Other problems with newborn', 50);
insert into Company (id, name, description, id_recruiter) values (41, 'Browsebug', 'Monoplegia of upper limb following other nontraumatic intracranial hemorrhage affecting right non-dominant side', 3);
insert into Company (id, name, description, id_recruiter) values (42, 'Avaveo', 'Other immunodeficiencies', 4);
insert into Company (id, name, description, id_recruiter) values (43, 'Skiba', 'Heat syncope, initial encounter', 32);
insert into Company (id, name, description, id_recruiter) values (44, 'Meevee', 'Blister (nonthermal) of anus, subsequent encounter', 47);
insert into Company (id, name, description, id_recruiter) values (45, 'Wordware', 'Acute respiratory distress syndrome', 32);
insert into Company (id, name, description, id_recruiter) values (46, 'Twiyo', 'Arthritis due to other bacteria, ankle and foot', 15);
insert into Company (id, name, description, id_recruiter) values (47, 'Edgeclub', 'Unspecified intracranial injury without loss of consciousness, initial encounter', 28);
insert into Company (id, name, description, id_recruiter) values (48, 'DabZ', 'Complications of reattached (part of) left upper extremity', 32);
insert into Company (id, name, description, id_recruiter) values (49, 'Leenti', 'Unspecified injury of unspecified intra-abdominal organ, subsequent encounter', 33);
insert into Company (id, name, description, id_recruiter) values (50, 'Skinder', 'Retained stone or crystalline fragments', 50);