insert into JobOffer (id, job_title, description, town, id_recruiter) values (1, 'Physical Therapy Assistant', 'Other chorioretinal scars', 'Gjilan', 1);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (2, 'Dental Hygienist', 'Dislocation of distal end of unspecified ulna', 'Evijärvi', 19);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (3, 'Pharmacist', 'Drowning and submersion while in bathtub, undetermined intent, sequela', 'Vredefort', 38);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (4, 'Marketing Assistant', 'Open wound of front wall of thorax with penetration into thoracic cavity', 'Miranda', 4);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (5, 'Staff Accountant I', 'Frostbite with tissue necrosis of unspecified toe(s)', 'Buzovna', 4);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (6, 'Human Resources Manager', 'Encounter for initial prescription of contraceptives', 'Türkmenbaşy', 20);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (7, 'Geological Engineer', 'Occupant of animal-drawn vehicle injured in collision with railway train or railway vehicle, initial encounter', 'Bailingnao', 7);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (8, 'Physical Therapy Assistant', 'Other balloon accident injuring occupant, initial encounter', 'Los Tangos', 50);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (9, 'Product Engineer', 'Complicated cataract', 'Taiqing', 43);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (10, 'Cost Accountant', 'Other coma, without documented Glasgow coma scale score, or with partial score reported, at arrival to emergency department', 'Balauring', 20);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (11, 'VP Quality Control', 'Military operations involving incendiary bullet, civilian, initial encounter', 'Suifenhe', 4);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (12, 'Payment Adjustment Coordinator', 'Other specified injuries left forearm, subsequent encounter', 'Gaoxu', 33);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (13, 'Administrative Assistant II', 'Other reactive arthropathies, ankle and foot', 'Daytona Beach', 7);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (14, 'Marketing Assistant', 'Unspecified injury of dorsal vein of right foot, initial encounter', 'Al Qurayshīyah', 2);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (15, 'Human Resources Manager', 'Legal intervention involving manhandling, suspect injured, subsequent encounter', 'Xinjie', 24);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (16, 'Structural Engineer', 'Fall (on)(from) incline, subsequent encounter', 'Manyava', 50);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (17, 'Structural Analysis Engineer', 'Displacement of other urinary devices and implants', 'Surin', 37);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (18, 'Social Worker', 'Nondisplaced transverse fracture of unspecified acetabulum, subsequent encounter for fracture with nonunion', 'La Libertad', 34);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (19, 'Operator', 'Unspecified subluxation of right shoulder joint, initial encounter', 'Oleiros', 14);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (20, 'Senior Editor', 'Other specified intracranial injury with loss of consciousness greater than 24 hours without return to pre-existing conscious level with patient surviving, sequela', 'Wucun', 20);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (21, 'Social Worker', 'Other mechanical complication of infusion catheter, initial encounter', 'Poggio di Chiesanuova', 2);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (22, 'Help Desk Technician', 'Legal intervention involving baton, law enforcement official injured, subsequent encounter', 'Pentéli', 23);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (23, 'Web Developer I', 'Personal history of estrogen therapy', 'San Felipe', 8);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (24, 'Internal Auditor', 'Other congenital deformities of feet', 'Khvorostyanka', 50);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (25, 'VP Quality Control', 'Type III traumatic spondylolisthesis of third cervical vertebra, subsequent encounter for fracture with routine healing', 'Karak', 3);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (26, 'Chemical Engineer', 'Toxic effect of lead and its compounds, undetermined, subsequent encounter', 'Candon', 41);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (27, 'Design Engineer', 'Other uterine inertia', 'Marne-la-Vallée', 10);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (28, 'Software Test Engineer I', 'Corrosion of unspecified degree of scapular region', 'Laixi', 20);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (29, 'Editor', 'Displaced fracture of base of unspecified metacarpal bone, subsequent encounter for fracture with nonunion', 'Caronoan West', 14);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (30, 'Research Assistant I', 'Other mature T/NK-cell lymphomas, intra-abdominal lymph nodes', 'Rokiciny', 48);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (31, 'Human Resources Assistant III', 'Corrosion of third degree of multiple sites of unspecified lower limb, except ankle and foot, subsequent encounter', 'Maigo', 23);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (32, 'Research Assistant IV', 'Vertigo from infrasound, sequela', 'Riyom', 14);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (33, 'Senior Cost Accountant', 'Displaced fracture of proximal phalanx of right index finger, initial encounter for closed fracture', 'Yambio', 1);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (34, 'Programmer I', 'Pediculosis and phthiriasis', 'Toulon', 42);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (35, 'Research Assistant IV', 'Other displaced fracture of sixth cervical vertebra, sequela', 'Tangyin', 26);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (36, 'Health Coach I', 'Poisoning by histamine H2-receptor blockers, intentional self-harm, sequela', 'Leticia', 35);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (37, 'Senior Cost Accountant', 'Burn of unspecified degree of unspecified toe(s) (nail), initial encounter', 'Siocon', 35);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (38, 'Pharmacist', 'Nondisplaced fracture of medial malleolus of left tibia, subsequent encounter for closed fracture with routine healing', 'Telgawah', 21);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (39, 'Safety Technician III', 'Other leukemias of specified cell type', 'Sangtian', 36);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (40, 'Programmer Analyst IV', 'Major laceration of superior vena cava, sequela', 'Paris 16', 33);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (41, 'Research Associate', 'Encounter for prophylactic removal of other organ', 'Vrbovec', 17);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (42, 'Web Developer IV', 'Other psychoactive substance use, unspecified with intoxication, unspecified', 'Medvedovskaya', 32);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (43, 'Financial Analyst', 'Adverse effect of unspecified psychotropic drug', 'Los Angeles', 6);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (44, 'Account Coordinator', 'Laceration of muscle, fascia and tendon of long head of biceps', 'Val-de-Reuil', 15);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (45, 'Environmental Specialist', 'Fracture of one rib, unspecified side, initial encounter for open fracture', 'Nagrog Wetan', 39);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (46, 'Developer III', 'Salter-Harris Type IV physeal fracture of right calcaneus, initial encounter for closed fracture', 'Wotan', 8);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (47, 'Project Manager', 'Superior glenoid labrum lesion of left shoulder, initial encounter', 'Yuelai', 35);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (48, 'Senior Cost Accountant', 'Methemoglobinemia', 'Ceelbuur', 28);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (49, 'Graphic Designer', 'Forced landing of glider (nonpowered) injuring occupant, sequela', 'Huaizhong', 25);
insert into JobOffer (id, job_title, description, town, id_recruiter) values (50, 'Operator', 'Chronic mastoiditis, right ear', 'Aserrí', 47);