INSERT INTO candidate VALUES (1,'dMNZInCCzgchfLlCHpGP','rV9+e7wPTC<*guL','Ellene','Giannasi','egiannasi0@prnewswire.com','884-691-0207','GbWlniNFisbEFmBTmAvVFzNjokZZsSrBmEVaCpaUXFLGjkyHMh');
INSERT INTO candidate VALUES (2,'RFCXvjgcLwaXDwZaWJLr','tA1{fK0TL{5','Donia','Camelia','dcamelia1@soundcloud.com','383-653-8270','');
INSERT INTO candidate VALUES (3,'gNQLSnpTEpqaNpndvYvk','tV6Y$2VD~','Anatol','Woodroofe','awoodroofe2@oracle.com','706-176-1960','OfhrQHastUOvjtaBscSNfOlvTiNZSdnjNlMPygeaHBgxnNbvtE');
INSERT INTO candidate VALUES (4,'jYPQJYSwbVRJocowRjaJ','pU4)~N0xc','Ryun','Bleier','rbleier3@samsung.com','230-660-7396','WoMxCUrgIcjoLEfWvKZXOBVYECItKKxWdicGaqDdOAskgBpAgj');
INSERT INTO candidate VALUES (5,'ThSXndmfredUoIItgAHe','yZ8+U33FSF|=2g','Witty','Robertot','wrobertot4@gizmodo.com','973-885-1010','AcpAdFquEVQKMrRYUnHjNazilfPgwaMGAZpZUqWJwdxhjmlwai');
INSERT INTO candidate VALUES (6,'EbqDFnBxeSddnavguwyG','hO0_Pzw)OBlHO6','Lynnelle','Copcott','lcopcott5@sogou.com','225-401-7168','UZEOiZoOyyFfWRdaknVcseSgBexWAxoKiSKybBdVDjLGYJZtMF');
INSERT INTO candidate VALUES (7,'PjsCRHMDBMljJkBdxVAL','lX1_(aSqiCicily','Legion','Legion','clegion6@geocities.jp','621-349-2207','DDFkiAHuPmmWYGywxstfkhnTvaSsgYdCCo');
INSERT INTO candidate VALUES (8,'nvcGoKQBmyzfflSFMPxU','rT2_n!k\E','Cecily','Verty','cverty7@walmart.com','428-992-6565','OnsMBgWVWTrFupXlMguGMeVBorQyWWwboDRJHisshXwRqOzzeq');
INSERT INTO candidate VALUES (9,'DnvUiFnEVPowoNNIKnbQ','iL7Y0NlfTf','Meghann','Scally','mscally8@smh.com.au','141-485-9884','UbxXDdRvGAAqeHxXBUqbYTFQWXYAhlsxxQstjkqSumnUqVXVjD');
INSERT INTO candidate VALUES (10,'kFZnKxQulzfhtoyjPKRq','jW9%Gpt2SJxbS((,Yancy','Dyet','Dyet','ydyet9@reference.com','832-725-9466','');
INSERT INTO candidate VALUES (11,'jPqwiwUtWiKIGsdDNWCt','kA5@|HPavMd8','Brietta','Beauman','bbeaumana@wikia.com','958-134-4105','FdutEKJIDKYvpfNrQOHjrXoCuQYgvbokZyRttbovcXZDnoUsey');
INSERT INTO candidate VALUES (12,'GUITUQZNJqTZevXEgxuT','mD6>L$ij$\NSo','Martita','Rudolf','mrudolfb@wsj.com','135-669-4293','dpHsknraRkwQFPYeUbPHzbmVjasgExhYIzqHFqsJHKhdGDnkUz');
INSERT INTO candidate VALUES (13,'jlSOpsskamlRowmXVTet','gT8%Ul?WTiS#,Biddie','Gland','Gland','bglandc@nature.com','604-269-2454','uIkEZomQZTACnwhBimgmJSbPNfaxZbjKGgvGVRFuKnWXUhiviJ');
INSERT INTO candidate VALUES (14,'RNLSGFWtunizPclNZIkB','wF5><tLtY*<){+,Camel','Nesbitt','Nesbitt','cnesbittd@home.pl','134-432-4667','');
INSERT INTO candidate VALUES (15,'vaHqWRaYtoDgpqsHyCZA','cQ3|RLQ|WsP<gTAK','Sharl','Hatrey','shatreye@ow.ly','737-501-5504','AIHTjciFbNdQyRMbnQdzBQQNuyWETyzljSxcpJtQnsxjEKcNxL');
INSERT INTO candidate VALUES (16,'soPGrzRteIOWuyjgrMLD','cR2~Enj3','Shermy','Ganter','sganterf@storify.com','145-479-0331','');
INSERT INTO candidate VALUES (17,'AHiMWUTJHSUYmYAAiUPV','kH9oQkG9A\\EdNe','Paulita','Oneil','poneilg@adobe.com','979-977-3851','FWYZmWXtWACCbpPSOBPCowUfWFdclkIIqFbFauJQCBeUOlzhnv');
INSERT INTO candidate VALUES (18,'BNpaAZuKFbCDySeNlHUo','cY3|PZs5@,Hubey','Broseke','Broseke','hbrosekeh@sphinn.com','763-897-1161','TAPvWWGBZALeUfQAguGEnyeWcaXJQZVHpGTGyodNRwDxvSWwGi');
INSERT INTO candidate VALUES (19,'eHbJQLLrjDWArbeoBrPy','bQ3*DTG4v9t','Donna','Nugent','dnugenti@youtube.com','411-634-3898','MTgzXHulKaZXgmzUvMCpSytsezGiIUdTVCTMuFsOKRJkZvcacx');
INSERT INTO candidate VALUES (20,'aSsdkAsIsZYVSNMKZrpG','hP3%ueIT','Elnar','Westoff','ewestoffj@salon.com','560-638-0201','CekdcwydQwGKyowatTkuKHESugOeIXGPFZtjXoRjJtScdMtMsv');


INSERT INTO recruiter VALUES (1,'yAEjdUruXwHDxIgOCAXu','"iT1}b*@LIqLtc"');
INSERT INTO recruiter VALUES (2,'UKPJcGCQlmOZmKiNnoQA','"hC1\5Y"k`N"');
INSERT INTO recruiter VALUES (3,'INNUICjDygbjvdfOCoqH','cH3\Rg|tba>SN5');
INSERT INTO recruiter VALUES (4,'lwhhVnYLMpOdRPLOCOjZ','vT0\@Fnh{');
INSERT INTO recruiter VALUES (5,'zRYFympQSHgZwCqRiVdJ','vT1)UzZ~+S0cD/i~');
INSERT INTO recruiter VALUES (6,'pvcFNvIwATjDiFkPLYjr','yM9=OsAGX');
INSERT INTO recruiter VALUES (7,'wWTVuDCDkvRanacmnNHl','dL8(Az.H4g>x|');
INSERT INTO recruiter VALUES (8,'HNtsqxjzPcucvTAyoBqE','aI5*9vqL\2`');
INSERT INTO recruiter VALUES (9,'xgdhGwLnMVpYGNcAVWca','aJ0+)CDE0/W#ss)A');
INSERT INTO recruiter VALUES (10,'YJipKHsoWkUqiQoziUBM','vI1&gz$Q');
INSERT INTO recruiter VALUES (11,'TDCkvNYKVVJOxSCPxIvX','gS0*O~B4`P');
INSERT INTO recruiter VALUES (12,'taOuGRHUObSlXSWJrGMl','kH9|friHF)');
INSERT INTO recruiter VALUES (13,'btaNOQVJYXEreKwkTdOk','dP8~bm2)EA0cS(F{');
INSERT INTO recruiter VALUES (14,'GYNLvEgHcHLUxeKYRLTF','"kS8<kS3?LP"');
INSERT INTO recruiter VALUES (15,'cStmQCGNyVLvCAiRQxHU','"yD8sFM(j"');
INSERT INTO recruiter VALUES (16,'IOgVMgSXfNlXaMJtyAqG','"bQ4*82\&`Cz"');
INSERT INTO recruiter VALUES (17,'giFjBLqleDywSIlduGtb','"xG6?g?ZtofD""{f"');
INSERT INTO recruiter VALUES (18,'hmPvxjOFMsqMTRctZZxt','gE8?*td!){+jlz0c');
INSERT INTO recruiter VALUES (19,'AvEsPCIoqJAYbKmWsgLT','eM4|S+Oc>');
INSERT INTO recruiter VALUES (20,'shcTYVwkiIYmhxPyENjr','"sT9""l6@.f7bv"');

INSERT INTO company VALUES (1,'JumpXS','Aenean sit amet justo. Morbi ut odio.',1);
INSERT INTO company VALUES (2,'Photobug','"Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus."',2);
INSERT INTO company VALUES (3,'Izio','"Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio."',3);
INSERT INTO company VALUES (4,'Buzzshare','"Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus."',4);
INSERT INTO company VALUES (5,'Omba','"Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis."',5);
INSERT INTO company VALUES (6,'Skaboo','"Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante."',6);
INSERT INTO company VALUES (7,'Devpulse','In eleifend quam a odio.',7);
INSERT INTO company VALUES (8,'Meedoo','"Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio."',8);
INSERT INTO company VALUES (9,'Zazio','"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus."',9);
INSERT INTO company VALUES (10,'Zava','"Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus."',10);
INSERT INTO company VALUES (11,'Tagchat','In eleifend quam a odio. In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.',11);
INSERT INTO company VALUES (12,'Skyba','Morbi porttitor lorem id ligula.',12);
INSERT INTO company VALUES (13,'Cogibox','Phasellus in felis. Donec semper sapien a libero. Nam dui.',13);
INSERT INTO company VALUES (14,'Nlounge','"In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus."',14);
INSERT INTO company VALUES (15,'Skyndu','"Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio."',15);
INSERT INTO company VALUES (16,'Jamia','"Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio."',16);
INSERT INTO company VALUES (17,'Oyonder','"Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris."',17);
INSERT INTO company VALUES (18,'Jatri','"Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc."',18);
INSERT INTO company VALUES (19,'Topiclounge','"Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus."',19);
INSERT INTO company VALUES (20,'Twitterlist','"Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris. Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis."',20);

INSERT INTO offer VALUES(1,'Suspendisse ornare consequat lectus. In est risus',' auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.','Indonesia','1');
INSERT INTO offer VALUES(2,'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue',' risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla.','China','2');
INSERT INTO offer VALUES(3,'In eleifend quam a odio.','In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.','Indonesia','3');
INSERT INTO offer VALUES(4,'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.','Mauris sit amet eros. Suspendisse accumsan tortor quis turpis. Sed ante. Vivamus tortor. Duis mattis egestas metus.','China','4');
INSERT INTO offer VALUES(5,'Aenean sit amet justo. Morbi ut odio. Cras mi pede','malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.','Argentina','5');
INSERT INTO offer VALUES(6,'Integer aliquet',' massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.','Indonesia','6');
INSERT INTO offer VALUES(7,'Praesent id massa id nisl venenatis lacinia.','malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.','Brazil','7');
INSERT INTO offer VALUES(8,'Donec dapibus.','Duis at velit eu est congue elementum.','Czech Republic','8');
INSERT INTO offer VALUES(9,'Nullam varius.','Duis at velit eu est congue elementum.','Jordan','9');
INSERT INTO offer VALUES(10,'Sed sagittis. Nam congue',' risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.','New Zealand','10');
INSERT INTO offer VALUES(11,'Morbi sem mauris',' laoreet ut, rhoncus aliquet, pulvinar sed, nisl.','France','11');
INSERT INTO offer VALUES(12,'Sed ante.','Vivamus tortor.','Indonesia','12');
INSERT INTO offer VALUES(13,'Maecenas tristique','est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.','Philippines','13');
INSERT INTO offer VALUES(14,'Nullam varius. Nulla facilisi.','Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.','Croatia','14');
INSERT INTO offer VALUES(15,'Donec vitae nisi. Nam ultrices','libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.','Nigeria','15');
INSERT INTO offer VALUES(16,'Curabitur gravida nisi at nibh.','In hac habitasse platea dictumst.','China','16');
INSERT INTO offer VALUES(17,'Integer a nibh. In quis justo.','Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.','Croatia','17');
INSERT INTO offer VALUES(18,'Praesent blandit lacinia erat.','Vestibulum sed magna at nunc commodo placerat.','Portugal','18');
INSERT INTO offer VALUES(19,'Praesent id massa id nisl venenatis lacinia.','Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.','Indonesia','19');
INSERT INTO offer VALUES(20,'Donec vitae nisi. Nam ultrices',' libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.','France','20');

INSERT INTO candidacy VALUES(9,14);
INSERT INTO candidacy VALUES(13,13);
INSERT INTO candidacy VALUES(12,8);
INSERT INTO candidacy VALUES(2,3);
INSERT INTO candidacy VALUES(7,2);
INSERT INTO candidacy VALUES(17,8);
INSERT INTO candidacy VALUES(16,20);
INSERT INTO candidacy VALUES(11,6);
INSERT INTO candidacy VALUES(2,17);
INSERT INTO candidacy VALUES(13,19);
INSERT INTO candidacy VALUES(20,6);
INSERT INTO candidacy VALUES(15,5);
INSERT INTO candidacy VALUES(4,20);
INSERT INTO candidacy VALUES(3,4);
INSERT INTO candidacy VALUES(15,17);
INSERT INTO candidacy VALUES(10,9);
INSERT INTO candidacy VALUES(8,18);
INSERT INTO candidacy VALUES(1,1);
INSERT INTO candidacy VALUES(13,17);
INSERT INTO candidacy VALUES(7,13);
INSERT INTO candidacy VALUES(14,10);
INSERT INTO candidacy VALUES(9,18);
INSERT INTO candidacy VALUES(10,6);
INSERT INTO candidacy VALUES(15,6);
INSERT INTO candidacy VALUES(1,15);
INSERT INTO candidacy VALUES(1,19);
INSERT INTO candidacy VALUES(9,20);
INSERT INTO candidacy VALUES(2,11);
INSERT INTO candidacy VALUES(2,19);
INSERT INTO candidacy VALUES(18,17);
INSERT INTO candidacy VALUES(18,16);
INSERT INTO candidacy VALUES(7,8);
INSERT INTO candidacy VALUES(7,6);
INSERT INTO candidacy VALUES(15,12);
INSERT INTO candidacy VALUES(20,4);
INSERT INTO candidacy VALUES(10,20);
INSERT INTO candidacy VALUES(19,13);
INSERT INTO candidacy VALUES(2,14);
INSERT INTO candidacy VALUES(16,7);
INSERT INTO candidacy VALUES(9,19);
INSERT INTO candidacy VALUES(19,14);
INSERT INTO candidacy VALUES(11,15);
INSERT INTO candidacy VALUES(16,5);
INSERT INTO candidacy VALUES(17,11);
INSERT INTO candidacy VALUES(12,7);
INSERT INTO candidacy VALUES(18,10);
INSERT INTO candidacy VALUES(6,13);
INSERT INTO candidacy VALUES(8,2);
INSERT INTO candidacy VALUES(7,8);
INSERT INTO candidacy VALUES(1,20);
INSERT INTO candidacy VALUES(15,18);
INSERT INTO candidacy VALUES(4,20);
INSERT INTO candidacy VALUES(4,3);
INSERT INTO candidacy VALUES(13,6);
INSERT INTO candidacy VALUES(20,13);
INSERT INTO candidacy VALUES(19,12);
INSERT INTO candidacy VALUES(14,19);
INSERT INTO candidacy VALUES(8,1);
INSERT INTO candidacy VALUES(16,19);
INSERT INTO candidacy VALUES(3,8);
INSERT INTO candidacy VALUES(13,13);
INSERT INTO candidacy VALUES(17,13);
INSERT INTO candidacy VALUES(1,1);
INSERT INTO candidacy VALUES(11,18);
INSERT INTO candidacy VALUES(15,11);
INSERT INTO candidacy VALUES(20,10);
INSERT INTO candidacy VALUES(12,20);
INSERT INTO candidacy VALUES(3,2);
INSERT INTO candidacy VALUES(13,2);
INSERT INTO candidacy VALUES(5,1);
INSERT INTO candidacy VALUES(11,10);
INSERT INTO candidacy VALUES(12,5);
INSERT INTO candidacy VALUES(13,3);
INSERT INTO candidacy VALUES(17,1);
INSERT INTO candidacy VALUES(5,1);
INSERT INTO candidacy VALUES(10,7);
INSERT INTO candidacy VALUES(4,5);
INSERT INTO candidacy VALUES(13,4);
INSERT INTO candidacy VALUES(9,20);
INSERT INTO candidacy VALUES(19,6);
INSERT INTO candidacy VALUES(2,19);
INSERT INTO candidacy VALUES(11,20);
INSERT INTO candidacy VALUES(18,11);
INSERT INTO candidacy VALUES(18,1);
INSERT INTO candidacy VALUES(1,8);
INSERT INTO candidacy VALUES(10,1);
INSERT INTO candidacy VALUES(7,18);
INSERT INTO candidacy VALUES(8,5);
INSERT INTO candidacy VALUES(5,10);
INSERT INTO candidacy VALUES(7,1);
INSERT INTO candidacy VALUES(14,3);
INSERT INTO candidacy VALUES(11,12);
INSERT INTO candidacy VALUES(10,6);
INSERT INTO candidacy VALUES(10,12);
INSERT INTO candidacy VALUES(1,10);
INSERT INTO candidacy VALUES(20,8);
INSERT INTO candidacy VALUES(13,6);
INSERT INTO candidacy VALUES(5,10);
INSERT INTO candidacy VALUES(16,20);
INSERT INTO candidacy VALUES(3,13);
INSERT INTO candidacy VALUES(2,10);
INSERT INTO candidacy VALUES(15,11);
INSERT INTO candidacy VALUES(1,11);
INSERT INTO candidacy VALUES(1,2);
INSERT INTO candidacy VALUES(14,3);
INSERT INTO candidacy VALUES(13,10);
INSERT INTO candidacy VALUES(6,6);
INSERT INTO candidacy VALUES(3,13);
INSERT INTO candidacy VALUES(14,16);
INSERT INTO candidacy VALUES(11,14);
INSERT INTO candidacy VALUES(19,10);
INSERT INTO candidacy VALUES(14,6);
INSERT INTO candidacy VALUES(16,15);
INSERT INTO candidacy VALUES(11,5);
INSERT INTO candidacy VALUES(20,7);
INSERT INTO candidacy VALUES(12,12);
INSERT INTO candidacy VALUES(1,2);
INSERT INTO candidacy VALUES(8,16);
INSERT INTO candidacy VALUES(3,16);
INSERT INTO candidacy VALUES(16,3);
INSERT INTO candidacy VALUES(15,8);
INSERT INTO candidacy VALUES(1,13);
INSERT INTO candidacy VALUES(6,16);
INSERT INTO candidacy VALUES(4,16);
INSERT INTO candidacy VALUES(3,18);
INSERT INTO candidacy VALUES(18,9);
INSERT INTO candidacy VALUES(14,17);
INSERT INTO candidacy VALUES(19,5);
INSERT INTO candidacy VALUES(11,13);
INSERT INTO candidacy VALUES(7,4);
INSERT INTO candidacy VALUES(7,18);
INSERT INTO candidacy VALUES(7,7);
INSERT INTO candidacy VALUES(19,15);
INSERT INTO candidacy VALUES(10,2);
INSERT INTO candidacy VALUES(18,12);
INSERT INTO candidacy VALUES(2,7);
INSERT INTO candidacy VALUES(13,9);
INSERT INTO candidacy VALUES(8,13);
INSERT INTO candidacy VALUES(17,19);
INSERT INTO candidacy VALUES(3,20);
INSERT INTO candidacy VALUES(12,11);
INSERT INTO candidacy VALUES(9,18);
INSERT INTO candidacy VALUES(3,8);
INSERT INTO candidacy VALUES(12,11);
INSERT INTO candidacy VALUES(14,4);
INSERT INTO candidacy VALUES(14,18);
INSERT INTO candidacy VALUES(8,3);
INSERT INTO candidacy VALUES(6,7);
INSERT INTO candidacy VALUES(2,17);
INSERT INTO candidacy VALUES(7,20);
INSERT INTO candidacy VALUES(18,5);
INSERT INTO candidacy VALUES(12,8);
INSERT INTO candidacy VALUES(13,1);
INSERT INTO candidacy VALUES(20,17);
INSERT INTO candidacy VALUES(12,8);
INSERT INTO candidacy VALUES(5,2);
INSERT INTO candidacy VALUES(16,10);
INSERT INTO candidacy VALUES(2,1);
INSERT INTO candidacy VALUES(5,14);
INSERT INTO candidacy VALUES(17,12);
INSERT INTO candidacy VALUES(20,3);
INSERT INTO candidacy VALUES(7,9);
INSERT INTO candidacy VALUES(19,9);
INSERT INTO candidacy VALUES(17,7);
INSERT INTO candidacy VALUES(7,13);
INSERT INTO candidacy VALUES(6,12);
INSERT INTO candidacy VALUES(2,10);
INSERT INTO candidacy VALUES(11,16);
INSERT INTO candidacy VALUES(11,5);
INSERT INTO candidacy VALUES(19,20);
INSERT INTO candidacy VALUES(3,1);
INSERT INTO candidacy VALUES(7,3);
INSERT INTO candidacy VALUES(1,8);
INSERT INTO candidacy VALUES(8,1);
INSERT INTO candidacy VALUES(19,17);
INSERT INTO candidacy VALUES(18,10);
INSERT INTO candidacy VALUES(6,18);
INSERT INTO candidacy VALUES(19,19);
INSERT INTO candidacy VALUES(1,15);
INSERT INTO candidacy VALUES(14,11);
INSERT INTO candidacy VALUES(2,14);
INSERT INTO candidacy VALUES(20,3);
INSERT INTO candidacy VALUES(14,12);
INSERT INTO candidacy VALUES(2,9);
INSERT INTO candidacy VALUES(14,14);
INSERT INTO candidacy VALUES(2,6);
INSERT INTO candidacy VALUES(9,18);
INSERT INTO candidacy VALUES(20,17);
INSERT INTO candidacy VALUES(19,6);
INSERT INTO candidacy VALUES(13,6);
INSERT INTO candidacy VALUES(7,5);
INSERT INTO candidacy VALUES(4,20);
INSERT INTO candidacy VALUES(2,3);
INSERT INTO candidacy VALUES(15,2);
INSERT INTO candidacy VALUES(19,15);
INSERT INTO candidacy VALUES(1,19);
INSERT INTO candidacy VALUES(16,11);
INSERT INTO candidacy VALUES(6,1);
INSERT INTO candidacy VALUES(14,12);
INSERT INTO candidacy VALUES(6,2);